sudo: required
services:
  - docker

before_install:
  - docker build -t bouatimelmahfoud/react-docker -f Dockerfile.dev .
 
script:
  - docker run bouatimelmahfoud/react-docker npm run test -- --coverage

