sudo: required
services:
  - docker

before_install:
  - docker build -t bouatimelmahfoud/react-docker -f Dockerfile.dev .
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
 
script:
  - docker run -e CI=true bouatimelmahfoud/react-docker npm run test 
deploy:
  provider: script
  script:
    docker build -t bouatimelmahfoud/react-prod  
    docker tag bouatimelmahfoud/react-prod registry.heroku.com/bouatim-react-docker/web
    docker push registry.heroku.com/bouatim-react-docker/web
  on:
    branch: master