sudo: required
services:
  - docker

before_install:
  - docker build -t bouatimelmahfoud/react-docker -f Dockerfile.dev .
 
script:
  - docker run -e CI=true bouatimelmahfoud/react-docker npm run test 
deploy:
  provider: heroku
  api_key: "46fd2784-9958-4bd1-ac83-8c67570d381f"
  app: bouatim-react-docker
  on:
    branch: master