sudo: required
services:
  - docker

before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - docker build -t bouatimelmahfoud/react-docker -f Dockerfile.dev .
 
script:
  - docker run -e CI=true bouatimelmahfoud/react-docker npm run test 
deploy:
  provider: script
  script:
    docker build -t bouatimelmahfoud/react-prod . ;
    echo 46fd2784-9958-4bd1-ac83-8c67570d381f | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com;
    docker tag bouatimelmahfoud/react-prod registry.heroku.com/bouatim-react-prod/web;
    docker push registry.heroku.com/bouatim-react-docker/web;
    heroku container:release web --app bouatim-react-docker
  on:
    branch: master